backend:
  name: github
  repo: hapakaien/me

media_folder: 'static/uploads'
public_folder: 'uploads'

collections:
  - name: 'blog_posts'
    label: 'Blog Posts'
    folder: 'content/blog/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'ID',
          name: 'id',
          widget: 'ncw-id',
          timestamp: true,
          hint: This widget generate an unique read-only id
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Post Author',
          name: 'author',
          widget: 'relation',
          collection: 'blog_authors',
          searchFields: ['title'],
          valueField: 'id',
          displayFields: ['title'],
        }
      - {
          label: 'Post Tag',
          name: 'tag',
          widget: 'relation',
          multiple: true,
          collection: 'blog_tags',
          searchFields: ['title'],
          valueField: 'id',
          displayFields: ['title'],
        }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog_tags'
    label: 'Blog Tags'
    folder: 'content/blog/tags'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'ID',
          name: 'id',
          widget: 'ncw-id',
          timestamp: true,
          hint: This widget generate an unique read-only id
        }
      - { label: 'Name', name: 'title', widget: 'string' }
  - name: 'blog_authors'
    label: 'Blog Authors'
    folder: 'content/blog/authors'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'ID',
          name: 'id',
          widget: 'ncw-id',
          timestamp: true,
          hint: This widget generate an unique read-only id
        }
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Blurb', name: 'blurb', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Github', name: 'github', widget: 'string' }
      - { label: 'Twitter', name: 'twitter', widget: 'string' }
      - { label: 'LinkedIn', name: 'linkedin', widget: 'string' }
      - { label: 'Author Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'portfolio_works'
    label: 'Portfolio Works'
    folder: 'content/portfolio/works'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'ID',
          name: 'id',
          widget: 'ncw-id',
          timestamp: true,
          hint: This widget generate an unique read-only id
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'URL', name: 'url', widget: 'string' }
      - {
          label: 'Work Tag',
          name: 'tag',
          widget: 'relation',
          multiple: true,
          collection: 'portfolio_tags',
          searchFields: ['title'],
          valueField: 'id',
          displayFields: ['title'],
        }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
  - name: 'portfolio_tags'
    label: 'Portfolio Tags'
    folder: 'content/portfolio/tags'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'ID',
          name: 'id',
          widget: 'ncw-id',
          timestamp: true,
          hint: This widget generate an unique read-only id
        }
      - { label: 'Name', name: 'title', widget: 'string' }
