# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build app
        env:
          GRIDSOME_GRAVATAR_URL: https://www.gravatar.com
          GRIDSOME_GRAVATAR_HASH: fd72a8fefdc8c5261e8a416f73bb0a18
          API_URL: ${{ secrets.API_URL }}
          GRIDSOME_API_URL: ${{ secrets.API_URL }}
          APP_GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
          GRIDSOME_DEVTO_URL: https://dev.to/api
          GRIDSOME_BLOG_URL: ${{ secrets.GRIDSOME_BLOG_URL }}
          GRIDSOME_FORMSPREE_ENDPOINT: ${{ secrets.GRIDSOME_FORMSPREE_ENDPOINT }}
        run: yarn build
        
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.1.1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
