name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env:
        GRIDSOME_GRAVATAR_URL: https://www.gravatar.com
        GRIDSOME_GRAVATAR_HASH: fd72a8fefdc8c5261e8a416f73bb0a18
        API_URL: ${{ secrets.API_URL }}
        GRIDSOME_API_URL: ${{ secrets.API_URL }}
        APP_GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
        GRIDSOME_DEVTO_URL: https://dev.to/api
        GRIDSOME_BLOG_URL: ${{ secrets.GRIDSOME_BLOG_URL }}
        GRIDSOME_FORMSPREE_ENDPOINT: ${{ secrets.GRIDSOME_FORMSPREE_ENDPOINT }}
    -   name: Build the Docker image
        run: docker build . -t husenisme/site
